import { ContractInterface, ApiContract } from "../types/contract";

export const mapToApiContract = (contract: ContractInterface) => ({
  id: contract.id,
  employee_id: contract.employeeId,
  contract_date: contract.contractDate,
  contract_end_date: contract.contractEndDate,
  contract_amount: contract.contractAmount,
  contract_content: contract.contractContent,
  contract_number: contract.contractNumber,
  full_name: contract.fullName,
  tax_id: contract.taxId,
  passport_series: contract.passportSeries,
  passport_number: contract.passportNumber,
  passport_issue_date: contract.passportIssueDate,
  passport_issued_by: contract.passportIssuedBy,
  organization_id: contract.organizationId,
  name: contract.name,
  shortName: contract.shortName,
  edrpouCode: contract.edrpouCode,
  legalAddress: contract.legalAddress,
  phone: contract.phone,
  bankAccount: contract.bankAccount,
  bankName: contract.bankName,
  foundationDoc: contract.foundationDoc,
  directorPosition: contract.directorPosition,
  directorFullName: contract.directorFullName,
});

export const mapFromApiContract = (
  contract: ApiContract
): ContractInterface => ({
  id: contract.id,
  employeeId: contract.employee_id,
  contractDate: contract.contract_date,
  contractEndDate: contract.contract_end_date,
  contractAmount: contract.contract_amount,
  contractContent: contract.contract_content,
  contractNumber: contract.contract_number,
  fullName: contract.full_name,
  taxId: contract.tax_id,
  passportSeries: contract.passport_series,
  passportNumber: contract.passport_number,
  passportIssueDate: contract.passport_issue_date,
  passportIssuedBy: contract.passport_issued_by,
  organizationId: contract.organization_id,
  name: contract.name,
  shortName: contract.short_name,
  edrpouCode: contract.edrpou_code,
  legalAddress: contract.legal_address,
  phone: contract.phone,
  bankAccount: contract.bank_account,
  bankName: contract.bank_name,
  foundationDoc: contract.foundation_doc,
  directorPosition: contract.director_position,
  directorFullName: contract.director_full_name,
});
